### ISSUE TITLE
Bug: Colorify not removing visual representation of color

### ISSUE THREAD

**Issue by Nanito111** [NvChad/ui#364]
Describe the bug
Colorify not removing visual representation of color after removing the color hex.

To Reproduce
Write hex color, Colorify showing visual representation of color, remove hex color.

Expected behavior
Visual representation of color getting removed.

Screenshots
https://github.com/user-attachments/assets/068762e3-5651-4af8-85b2-439ae1187b8b

Operating System:
Fedora Linux 40 (KDE Plasma) x86_64

Neovim Version:
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189

**Comment by siduck** [comment]
good bug, will look on it today!

**Comment by siduck** [comment]
till then use the bg mode of colorify. read `:h nvui.colorify`

**Comment by siduck** [comment]
unable to reproduce, u sure u are on latest commit of ui plugin?


https://github.com/user-attachments/assets/38c39a58-fa43-456e-9eac-e73bc72d08ca

**Comment by Nanito111** [comment]
![image](https://github.com/user-attachments/assets/deca3ed9-9490-4c78-b47d-cd80d92828cd)
I confirm that im on last commit of UI plugin.

I check that it doens't happen with lua files. I also check with css files like u did and it happens.

**Comment by Nanito111** [comment]
```
Error executing vim.schedule lua callback: ...local/share/nvim/lazy/ui/lua/nvchad/colorify/methods.lua:67: Invalid 'end_col': out of range                      
stack traceback:                                                                                                                                                
        [C]: in function 'set_extmark'                                                                                                                          
        ...local/share/nvim/lazy/ui/lua/nvchad/colorify/methods.lua:67: in function 'handler'                                                                   
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''                                                                                      
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
I got this error log

**Comment by Spell28** [comment]
Same problem, some times i see this traceback
<img width="1048" alt="Снимок экрана 2024-12-10 в 16 18 14" src="https://github.com/user-attachments/assets/5d51b2db-50fa-4edb-a6de-9bd9dbad39f2">

**Comment by siduck** [comment]
produce a video so i can reproduce

**Comment by Spell28** [comment]
I don't understand why is traceback is shown and specially call this traceback is impossible for me....
I will watch carefully and maybe I will find a pattern then I will come back here

**Comment by Spell28** [comment]
@siduck i got this, for me this should be after insert [codeium](https://github.com/Exafunction/codeium.vim) suggestion

https://github.com/user-attachments/assets/4481e7ba-1f8e-4605-8714-bc8c1eee54bc

**Comment by siduck** [comment]
nice, will debug

**Comment by siduck** [comment]
unable to reproduce, can you share a minimal file with vid?

**Comment by Nanito111** [comment]
I just reinstalled everything including nvim and nvchad, and now I don't have this problem anymore, maybe there was something wrong with my nvchad installation ¿? idk to be honest haha

**Comment by siduck** [comment]
ohh, if someone reproduces with minimal file+vid then i'll debug this @Spell28

**Comment by Spell28** [comment]
Now I'll try to create a repository with a minimal example and video

**Comment by Spell28** [comment]
@siduck  Copy the css file below to any directory, create a line with two spaces and shift+v and do yank, then just hold down the p button to paste as in the example video

P.S: I'm going to try it on pure nvchad now.
P.S.S: I confirm that there is also an error on a clean nvchad, @siduck I also think you should check this on a weak laptop..


https://github.com/user-attachments/assets/afb44667-91cb-48d2-8d06-5012805c49f8




<details><summary>Some css</summary>
<p>

```css
:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;

  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

a {
  font-weight: 500;
  color: #646cff;
  text-decoration: inherit;
}
a:hover {
  color: #535bf2;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}
button:hover {
  border-color: #646cff;
}
button:focus,
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}

@media (prefers-color-scheme: light) {
  :root {
    color: #213547;
    background-color: #ffffff;
  }
  a:hover {
    color: #747bff;
  }
  button {
    background-color: #f9f9f9;
  }
}

```

</p>
</details>
